#!/usr/bin/env python3
"""Pure incident-recovery tests: never run iptables or touch live services."""

import importlib.util
import ipaddress
from pathlib import Path
import shlex
import unittest
from unittest.mock import patch


REPO = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "la_loopback_recovery", REPO / "scripts/recover-la721-firewall-inflight.py")
m = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(m)

FIXTURE = REPO / "tests/fixtures/la721-firewall-20260913"
ORIGINAL = (FIXTURE / "iptables.filter.raw").read_bytes()
DROP = (
    b"-A INPUT -p tcp -m tcp --dport 20382 -m comment "
    b"--comment argo-rr-managed-block -j DROP\n"
)
ALLOW = (
    b"-A INPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -i lo -p tcp -m tcp "
    b"--dport 20382 -m comment --comment rr-la721-loopback -j ACCEPT\n"
)


class PacketEvaluator:
    """Independent first-match evaluator for the concrete incident grammar.

    This does not use any recovery parser, policy projection or predicates.
    Unsupported rules fail the test instead of silently behaving as ACCEPT.
    """

    def __init__(self, program):
        self.policies = {}
        self.rules = {}
        for line in program.decode("ascii").splitlines():
            words = shlex.split(line)
            if words[0] == "-P":
                assert len(words) == 3
                self.policies[words[1]] = words[2]
                continue
            assert words[:1] == ["-A"]
            rule = {"protocol": None, "port": None, "interface": None,
                    "source": None, "destination": None, "verdict": None}
            index = 2
            while index < len(words):
                option, value = words[index:index + 2]
                if option == "-p":
                    rule["protocol"] = value
                elif option == "--dport":
                    rule["port"] = int(value)
                elif option == "-i":
                    rule["interface"] = value
                elif option in ("-s", "-d"):
                    key = "source" if option == "-s" else "destination"
                    rule[key] = ipaddress.ip_network(value)
                elif option == "-j":
                    assert value in ("ACCEPT", "DROP")
                    rule["verdict"] = value
                else:
                    assert option in ("-m", "--comment"), option
                    if option == "-m":
                        assert value in ("tcp", "udp", "comment"), value
                index += 2
            assert rule["verdict"] is not None
            self.rules.setdefault(words[1], []).append(rule)

    def decisions(self, chain, interface, source, destination, protocol):
        """Compute all port verdicts by evaluating each packet in rule order."""
        source = ipaddress.ip_address(source)
        destination = ipaddress.ip_address(destination)
        applicable = []
        for rule in self.rules.get(chain, []):
            if rule["protocol"] not in (None, protocol):
                continue
            if rule["interface"] not in (None, interface):
                continue
            if rule["source"] is not None and source not in rule["source"]:
                continue
            if rule["destination"] is not None and destination not in rule["destination"]:
                continue
            applicable.append((rule["port"], rule["verdict"]))
        result = []
        for port in range(65536):
            verdict = self.policies[chain]
            for match_port, match_verdict in applicable:
                if match_port is None or match_port == port:
                    verdict = match_verdict
                    break
            result.append(verdict)
        return result


def saved_parts(*, counters=False):
    """Include an identical DROP in another table to catch global replacement."""
    prefix = (
        b"# Generated by iptables-save on incident fixture\n"
        b"*mangle\n"
        b":PREROUTING ACCEPT [11:1234]\n"
        b":INPUT ACCEPT [12:2345]\n"
        b":FORWARD ACCEPT [0:0]\n"
        b":OUTPUT ACCEPT [13:3456]\n"
        b":POSTROUTING ACCEPT [0:0]\n"
        + DROP + b"COMMIT\n"
        b"# Table separator must survive exactly\n\n"
    )
    lines = [b"*filter\n", b"# Keep filter accounting and comments\n"]
    for index, line in enumerate(ORIGINAL.splitlines(keepends=True)):
        words = line.split()
        if words[0] == b"-P":
            lines.append(b":" + words[1] + b" " + words[2]
                         + (" [%d:%d]\n" % (index + 14, (index + 14) * 128)).encode())
        else:
            if counters:
                line = ("[%d:%d] " % (index, index * 128)).encode() + line
            lines.append(line)
            if b"--dport 443 " in line:
                lines.append(b"# Preserve this comment between filter rules\n")
    lines.extend([b"COMMIT\n", b"# Completed filter fixture\n"])
    suffix = (
        b"*nat\n"
        b":PREROUTING ACCEPT [21:4096]\n"
        b":INPUT ACCEPT [0:0]\n"
        b":OUTPUT ACCEPT [22:8192]\n"
        b":POSTROUTING ACCEPT [0:0]\n"
        b"-A OUTPUT -d 198.51.100.8/32 -p tcp -m tcp --dport 20382 "
        b"-j DNAT --to-destination 192.0.2.8:20382\n"
        b"COMMIT\n# Completed by iptables-save\n"
    )
    return prefix, b"".join(lines), suffix


class LoopbackRecoveryTests(unittest.TestCase):
    def test_raw_candidate_is_exactly_one_rule_before_original_drop(self):
        self.assertEqual(m.sha(ORIGINAL), m.RAW_PINS["iptables.filter"])
        candidate = m.loopback_raw_candidate(ORIGINAL)
        self.assertEqual(candidate, ORIGINAL.replace(DROP, ALLOW + DROP, 1))
        self.assertEqual(candidate.count(ALLOW), 1)
        self.assertEqual(candidate.replace(ALLOW, b"", 1), ORIGINAL)
        self.assertEqual(candidate.count(DROP), 1)

    def test_first_match_only_changes_exact_ipv4_loopback_subscription_packets(self):
        before = PacketEvaluator(ORIGINAL)
        after = PacketEvaluator(m.loopback_raw_candidate(ORIGINAL))
        contexts = [
            ("lo", "127.0.0.1", "127.0.0.1"),
            ("eth0", "127.0.0.1", "127.0.0.1"),
            ("eth0", "198.51.100.7", "192.0.2.8"),
            ("eth0", "198.51.100.7", "127.0.0.1"),
            ("lo", "127.0.0.2", "127.0.0.1"),
            ("lo", "127.0.0.1", "127.0.0.2"),
            ("lo", "127.1.2.3", "127.1.2.3"),
            ("lo", "198.51.100.7", "127.0.0.1"),
            ("lo", "127.0.0.1", "192.0.2.8"),
        ]
        for chain in ("INPUT", "FORWARD", "OUTPUT"):
            for context in contexts:
                for protocol in ("tcp", "udp", "icmp"):
                    with self.subTest(chain=chain, context=context, protocol=protocol):
                        original = before.decisions(chain, *context, protocol)
                        candidate = after.decisions(chain, *context, protocol)
                        expected = original.copy()
                        if chain == "INPUT" and context == contexts[0] and protocol == "tcp":
                            self.assertEqual(original[20382], "DROP")
                            expected[20382] = "ACCEPT"
                        self.assertEqual(candidate, expected)

    def test_raw_candidate_refuses_unknown_duplicate_and_wrong_family_inputs(self):
        candidate = m.loopback_raw_candidate(ORIGINAL)
        bad_programs = {
            "already_patched": candidate,
            "duplicate_allow": candidate.replace(ALLOW, ALLOW + ALLOW),
            "missing_drop": ORIGINAL.replace(DROP, b""),
            "duplicate_drop": ORIGINAL + DROP,
            "changed_input_policy": ORIGINAL.replace(b"-P INPUT ACCEPT", b"-P INPUT DROP"),
            "changed_other_chain": ORIGINAL.replace(b"-P OUTPUT ACCEPT", b"-P OUTPUT DROP"),
            "unknown_extra_rule": ORIGINAL + b"-A INPUT -j DROP\n",
            "whitespace_only_drift": ORIGINAL + b"\n",
            "wrong_family": (FIXTURE / "ip6tables.filter.raw").read_bytes(),
        }
        for name, program in bad_programs.items():
            with self.subTest(name=name), self.assertRaises(m.Refused):
                m.loopback_raw_candidate(program)

    def test_saved_candidate_preserves_other_tables_comments_and_counters(self):
        for counters in (False, True):
            with self.subTest(rule_counters=counters):
                prefix, table, suffix = saved_parts(counters=counters)
                target = next(line for line in table.splitlines(keepends=True)
                              if line.endswith(DROP))
                expected = prefix + table.replace(target, ALLOW + target, 1) + suffix
                saved = prefix + table + suffix
                result = m.loopback_persistence_candidate(saved, ORIGINAL)
                self.assertEqual(result, expected)
                self.assertEqual(result.replace(ALLOW, b"", 1), saved)
                self.assertEqual(result.count(ALLOW), 1)

    def test_saved_candidate_rejects_incomplete_ambiguous_or_different_filter(self):
        prefix, table, suffix = saved_parts()
        saved = prefix + table + suffix
        bad_files = {
            "missing_filter": prefix + suffix,
            "duplicate_filter": prefix + table + table + suffix,
            "nested_table": prefix + table.replace(b"COMMIT\n", b"*nat\nCOMMIT\n", 1) + suffix,
            "unterminated_filter": prefix + table.replace(b"COMMIT\n", b"", 1) + suffix,
            "stray_commit": b"COMMIT\n" + saved,
            "extra_commit": saved + b"COMMIT\n",
            "missing_drop": saved.replace(DROP, b""),
            "duplicate_filter_drop": prefix + table.replace(DROP, DROP + DROP) + suffix,
            "changed_policy": prefix + table.replace(b":INPUT ACCEPT", b":INPUT DROP") + suffix,
            "missing_chain": prefix + table.replace(b":OUTPUT ACCEPT [16:2048]\n", b"") + suffix,
            "duplicate_chain": prefix + table.replace(b":INPUT ACCEPT [14:1792]\n",
                                                       b":INPUT ACCEPT [14:1792]\n" * 2) + suffix,
            "different_port": prefix + table.replace(b"--dport 443 ", b"--dport 444 ") + suffix,
            "different_rule_action": prefix + table.replace(DROP, DROP.replace(b"-j DROP", b"-j ACCEPT")) + suffix,
            "additional_rule": prefix + table.replace(DROP, b"-A INPUT -j ACCEPT\n" + DROP) + suffix,
            "reordered_rules": prefix + table.replace(DROP, b"").replace(
                b"# Keep filter accounting and comments\n",
                b"# Keep filter accounting and comments\n" + DROP) + suffix,
            "unknown_command": prefix + table.replace(DROP, b"-F INPUT\n" + DROP) + suffix,
            "already_patched": prefix + table.replace(DROP, ALLOW + DROP) + suffix,
            "malformed_counter": prefix + table.replace(b"[14:1792]", b"[oops:1792]") + suffix,
            "trailing_uncommitted_table": saved + b"*raw\n:PREROUTING ACCEPT [0:0]\n",
            "non_ascii_filter": prefix + table.replace(DROP, b"\xff\n" + DROP) + suffix,
        }
        for name, contents in bad_files.items():
            with self.subTest(name=name):
                self.assertNotEqual(contents, saved, "bad fixture failed to alter the original")
                with self.assertRaises(m.Refused):
                    m.loopback_persistence_candidate(contents, ORIGINAL)

    def test_saved_candidate_refuses_unknown_raw_even_if_save_matches_it(self):
        prefix, table, suffix = saved_parts()
        drifted_raw = ORIGINAL.replace(b"--dport 443 ", b"--dport 444 ")
        drifted_save = prefix + table.replace(b"--dport 443 ", b"--dport 444 ") + suffix
        with self.assertRaises(m.Refused):
            m.loopback_persistence_candidate(drifted_save, drifted_raw)

    def test_candidate_planning_does_not_invoke_commands_or_write_files(self):
        prefix, table, suffix = saved_parts()
        with patch.object(m.subprocess, "run", side_effect=AssertionError("must be pure")), \
             patch.object(m, "atomic_write", side_effect=AssertionError("must be pure")):
            m.loopback_raw_candidate(ORIGINAL)
            m.loopback_persistence_candidate(prefix + table + suffix, ORIGINAL)


if __name__ == "__main__":
    unittest.main()
